### ISSUE TITLE
Issue QAM parameter (DVB-C)

### ISSUE THREAD

**Issue by ghost** [vdomin/HDHRProxyIPTV#4]
Hi dsaupf (and vdomin for initial program), first of all, great work!

I tested it with minisatip and for channels with QAM64 it works, but not for QAM256.
 I only see QAM64 type in HDHomeRun config GUI in Physical channel even if mtype=256qam is set in SAT>IP URL. Can you please fix this issue so QAM type will be extracted from SAT>IP URL? So, mtype parameter must also be transmitted to minisatip for compatibility with devices which do not auto-detect modulation type.

Thank you!

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

In order to force an specific modulation, you only need to edit the “URLGet” parameter in the MappingList file. The configuration parameter “SYS_MODEL” is used only when advertizing the HDHR emulated device, and not when doing the SAT>IP requests.

Example:

- INI File:
```
[HDHR_SYS_CONFIG]
SYS_MODEL="hdhomerun_dvbc"
SYS_DVBC_MODULATION="qam256"
...
```

- MappingList File:
```
[CH1]
Channel=21
LowFreq=172646000
HighFreq=172646000
Protocol=HTTP
URLGet=http://my-satip-server:8080/?msys=dvbs&freq=11627&pol=v&sr=22000
UDPsource=
InternalPIDFiltering=Y
ExternalPIDFiltering=Y
Signal_Strength=95
Signal_Quality=95
Symbol_Quality=100
Network_Rate=30000000
Program_table=[0:0:19.2 11627V RTVE][4422:3946:CNN Int. SD,SES:0,17,18,3946,165,100][4430:273:DW SD,DW:0,17,18,273,529,785][4401:3520:TVE INT. EUROPA SD,RTVE:0,17,18,3520,3521,3522,3525,3526,3527,3528][4402:3568:CANAL 24 HORAS SD,RTVE:0,17,18,3568,3569,3570,3571,3575,3576,3577][tsid = 0x0404]
```

So, if you want to tune some “QAM256” transponder/frequency then you need to use the correct SAT>IP request syntax in the “URLGet” parameter like this:

`URLGet=http://my-satip-server:8080/?freq=514&sr=6900&msys=dvbc&mtype=256qam&fec=35`

I hope this helps you!
Regards.

**Comment by ghost** [comment]
Hi dsaupf, thanks for your fast reply, much appreciated!
I tried, but it still does lock on qam64.
I changed the INI file.
However, the HDHomeRun normally does auto-detect modulation type, but for SAT>IP protocol the mtype parameter with modulation is mandatory.

By the way, the FEC parameter isn't allowed for DVB-C and the SAT>IP URL has the pids parameter included.

**Comment by ghost** [comment]
By the way, why is the TSID noted in hex instead of decimal for Program_table in Mapping_List? Is it needed? Maybe it can be set to decimal? This is easier for me ;-)

Program_table=[20044:607:Brava:0,16,17,18,20,2900,2901,2911] [tsid = 0x0803]

**Comment by retrofan1979** [comment]
BTW, great project! Keep up the good work!

**Comment by ghost** [comment]
The modulation type is now locked all the time at qam64 even if I specify the modulation type in SAT>IP URL which is mandatory.

![image](https://user-images.githubusercontent.com/30625590/29561635-77b83c60-8736-11e7-8c24-b8cbc4791ff2.png)

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> By the way, why is the TSID noted in hex instead of decimal for Program_table in Mapping_List?
> Is it needed?

This is because the HDHR device sends the "tsid" value in HEX format.
It will be possible to update the code to support HEX and DEC values. However, it's quite easy to calculate.
In fact, all the info in the Program_table is optional. The HDHR device can return a message with this info. Then if you want the best compatibility then you need to complete this info.
However, you can leave blank if your client software doesn't use this message.

> I tried, but it still does lock on qam64.

Please, think on this: the modulation advertized by the HDHR emulator doesn't need to be in pair with the SAT>IP modulation.

You can configure the HDHR emulator with QAM64, and configure the frequencies with QAM256.
Example:

```
[CH33]
Channel=834
LowFreq=834000000
HighFreq=835000000
Protocol=HTTP
URLGet=http://192.168.0.5:8080/freq=834.75&msys=dvbc&mtype=256qam&sr=6900
InternalPIDFiltering=N
ExternalPIDFiltering=Y
Signal_Strength=100
Signal_Quality=100
Symbol_Quality=100
Program_table=[20044:607:Brava:0,16,17,18,20,2900,2901,2911] [tsid = 0x0803]
```

```
[HDHR_DEVICE]
FULL_TS_REPLACE="0,1,2,10,11,12,13,14,16,17,18,20"
[HDHR_SYS_CONFIG]
SYS_MODEL="hdhomerun_dvbc"
SYS_DVBC_MODULATION="qam64"
```

Your error is add the "pids" parameter in the URLGet... Both, the SAT>IP and HDHR have support for live changing of pid filtering. Also, if your SAT>IP server is minisatip, then you can change the pid list even with the HTTP transport. In this case, set "ExternalPIDFiltering" to YES (and disable the internal). But, if you use another SAT>IP server without support for multi HTTP requests with live-streaming, then disable the External PID filtering. In this case, you can use the "pids" parameter (for example with "pids=all") and enable the Internal PID filtering. Or you can output as SPTS in each frequency selecting the pids of each service. You can configure it in multiple ways!

Futhermore, note the FULL_TS_REPLACE option in the INI. You can use it for remap the full TS when some HDHR client requests it. Typically, with DVB you need to pass pids from 0 to 20.

Regards.

**Comment by ghost** [comment]
Hi, yes, minisatip is my SAT>IP server. ;-)
I changed the settings as you suggested, but with the same result. QAM stays 64. However, with your settings the HDHRProxy stops streaming after 20 seconds. With the previous settings (pids 0,16,17,18,20) which I had, the stream stays alive with hdhomerun config GUI when viewing with Windows Media Player.
BTW, what's the function of those other pids 1,2,10,11,12,13 and 14?

Could it be that qam64 is hardcoded in the sources? I did take a look in it and didn't find qam256.

You said: The HDHR device can return a message with this info -> Program Table. How to do this?
With hdhomerun_config <id> set /tuner0/program?

Thanks!

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> Hi, yes, minisatip is my SAT>IP server. ;-)

Ok. Then use 'ExternalPIDFiltering=Y' and 'InternalPIDFiltering=N' in all the Mappings.

> I changed the settings as you suggested, but with the same result. QAM stays 64. However, with your settings the HDHRProxy stops streaming after 20 seconds.

As physical HDHomeRuns do the emulator stops after some time of inactivity.
Please, enable the log level 3 or 4 and see the commands send to your SAT>IP server. Also check the status window of the Emulator.

> With the previous settings (pids 0,16,17,18,20) which I had, the stream stays alive with hdhomerun config GUI when viewing with Windows Media Player.

I'm using WMC too!
However, be aware with it. Sometimes it generates a large pid list. If your SAT>IP server doesn't support more than 32 pids, then you can have problems. I recommend first to check your configuration using only the HDHR Config GUI and the VLC as viewer. When all is working, then configure the WMC.

> BTW, what's the function of those other pids 1,2,10,11,12,13 and 14?

http://en.wikipedia.org/wiki/MPEG_transport_stream
Check the section "Packet Identifier".

> Could it be that qam64 is hardcoded in the sources? I did take a look in it and didn't find qam256.

No, is not! In the INI you can configure the HDHR model. Then in the URLGet you configure your precise tunning parameters. The Emulator doesn't do any "automatic" translation... except with the PID filtering if you enable "ExternalPIDFiltering=Y". All other tunning parameters are static and user configurable.

> You said: The HDHR device can return a message with this info -> Program Table. How to do this?
> With hdhomerun_config set /tuner0/program?

`hdhomerun_config deviceID get /tuner0/streaminfo`

This is only informative. As the emulator doesn't process the TS, it sends the data configured in the Mapping List.

Regards.

**Comment by ghost** [comment]
No, I'm using WMP (not WMC) for testing right now ;-) Should be the same as VLC.
However, still no luck. No matter what I try, I Always get QAM 64. Also tried another receiver with DVB-C tuners. The same result!

Any chance for you to test it yourself with DVB-C QAM256?

Can I also emulate HDHR3-4DC? With which setting?

Does HDHomeRun support frequencies ending at .75 MHz instead of .00 MHz? Probably, but just in case.

Regards

**Comment by ghost** [comment]
No chance the config GUI tool will also display QAM256?
https://user-images.githubusercontent.com/30625590/29561635-77b83c60-8736-11e7-8c24-b8cbc4791ff2.png

By the way, only FULL_TS_REPLACE="0,16,17,18,20" does work over here, not FULL_TS_REPLACE="0,1,2,10,11,12,13,14,16,17,18,20".

Those 0,16,17,18,20 pids are indeed the same as from the SAT>IP URLs.

Maybe still a bug somewhere in the sources? Could you please investigate?

Thanks!

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> No chance the config GUI tool will also display QAM256?

As I say before: don't worry if the HDHR Config GUI displays QAM64 ! This is only from the point of view of the client that connects to the HDHR Emulator. The real modulation (the *used* modulation) is the one used by the SAT>IP server. So you need to indicate "mtype=256qam" in your URLGet.

> By the way, only FULL_TS_REPLACE="0,16,17,18,20" does work over here, not FULL_TS_REPLACE="0,1,2,10,11,12,13,14,16,17,18,20".

OK. You can configure it as you need. This pid list it's used only when your HDHR client request the full TS. The HDHR emulator is then requesting only these pids to the SAT>IP server.

To be more effective. Please, can you share your INI and Mapping List files?
I feel you have an invalid configuration. Example:

`URLGet=http://192.168.0.5:8080/?freq=834.75&msys=dvbc&mtype=256qam&sr=6900`

You miss here the '?' character.
Are you checking the logs?

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> Any chance for you to test it yourself with DVB-C QAM256?

No. Sorry! Only DVB-T & DVB-S.

> Can I also emulate HDHR3-4DC? With which setting?

Yes. If you provide the correct values in the INI file.
Personally I don't know the values for this device.

> Does HDHomeRun support frequencies ending at .75 MHz instead of .00 MHz? Probably, but just in case.

If the client requests using frequency Hz, then Yes.

In any case, you can do the same as I do: Configure the HDHR emulator as a DVB-T server, and configure the URLGet for request whatever you need (DVB-C, DVB-S, DVB-T, IPTV). Using this thecnique I'm mapping DVB-S transponders to DVB-T muxes.

Regards.

**Comment by ghost** [comment]
About HDHR Config GUI: yes, you're right, but it would be cool if the emulator could extract the mtype from SAT>IP URL, so it displays the correct setting :-) But indeed, not needed ofcourse.
I use the '?' character, so also that's correct.

Thanks!

**Comment by retrofan1979** [comment]
Hmm, too bad you don't have DVB-C. I'm curious about this specific issue with modulation. Maybe a friend of yours?

Also LowFreq and HighFreq are correct? With both 834750000 it doesn't work.

**Comment by ghost** [comment]
By the way, is TSID the same as Stream ID?
If you could change hex notation to decimal, that would be great. Then I don't need to calculate them but just taking them from DVBViewer. ;-)

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> By the way, is TSID the same as Stream ID?

Yes, it is!

> Also LowFreq and HighFreq values are correct? With both 834750000 it doesn't work.

The idea behind these two values is define a range. If your client requests to tune _any_ frequency in the range, then the emulator will provide this channel.

> it would be cool if the emulator could extract the mtype from SAT>IP URL, so it displays the correct setting

But this behaviour will breaks the concept of this emulator: all the tunning parameters are **static** and **configurable**.


And regarding your configuration, it seems to be correct. However, some recomendations:

- Define a range for each frequency, like this:
```
[CH1]
Channel=164
LowFreq=163100000
HighFreq=164900000

[CH2]
Channel=834
LowFreq=833100000
HighFreq=834900000
```

- Check your configuration using some tool like TSReader, VLC or DVBlast. Example:

```
URLGet=http://192.168.0.6:8080/?freq=164.00&msys=dvbc&mtype=64qam&sr=6900
Program_table=[16181:997:Testbeeld:0,16,17,18,20,500,1501] [tsid = 0x0839]

Check with the tool: "http://192.168.0.6:8080/?freq=164.00&msys=dvbc&mtype=64qam&sr=6900&pids=0,16,17,18,20,500,1501"
And see if the PMT, SID, etc. are right.
For example, if Program_Table="[16181:997:Testbeeld:0,16,17,18,20,500,1501]" you describe a SID=16181 and PMT=997, therefore the pid of the PMT should be included in the pid list: "0,16,17,18,20,500,997,1501"
```

- If your DVB-C channels are MPTS, try to describe the full PAT in the Program_Table.
(See https://github.com/dsaupf/HDHRProxyIPTV/blob/master/Release/HDHRProxyIPTV_MappingList.ini)
```
Program_table=[805:110:TV3:0,1,16,17,18,19,110,111,112,114,116,801,811,905,129][806:120:Super3/33:0,120,121,122,124,126,129,814,906][807:130:3/24:0,130,131,132,134,136,129,807,907][808:230:Esport3:0,230,171,141,142,144,146,129,804,908][811:0:Cat Music:0,170,171][812:0:iCat.cat:0,180,181][813:190:TV3HD:0,190,191,192,194,196,805,815,129,913][tsid = 0x0065]
```

...


Finally, I feel that your problem now is the missing PMT pid in your channel description. So, if you use the HDHR Config GUI then compose a correct "Program_Table".

Regards.

**Comment by ghost** [comment]
Hi @dsaupf

You never believe this! It works! It seems WMP (Windows Media Player) doesn't play my QAM256 channels, only QAM64. When I installed VLC it did work right away. Also VLC is much faster with opening channels as it uses UDP protocol instead of RTP protocol.

It seems the LowFreq and HighFreq frequencies both work: your method and mine as well, so that not an issue. All settings were okay I had even TSID and PMT!

My suggestions for improving the project:
- add possibility to input TSID in both decimals or hex
- support for modulation entry in IPTV_MappingList.INI for each channel (optional) which will be displayed in Config GUI (not actual modulation, but just as text so it looks like it's emulated correctly ;-)).

For example:

[CH1]
Channel=834
LowFreq=833000000
HighFreq=834000000
Modulation=a8qam256-6900

Config GUI will show:
a8qam256-6900 : 834

For real modulation it will use the GetURL.
Thanks for your help so far and keep up the great work!

**Comment by ghost** [comment]
@dsaupf 
I also tried the Android app InstaTV (http://instatv.org/) which has native HDHomeRun support to check if it works and it does! (in default free version you only get video, is app-in purchase for audio playback).

**Comment by ghost** [comment]
And I get this error when using the HDHomeRun setup tool:

![image](https://user-images.githubusercontent.com/30625590/29652507-01d1daee-88a6-11e7-97b2-c232fe71203c.png)

Do you also get this error? Is this normal behaviour?

**Comment by dsaupf** [comment]
Hi @retrofan1979 ,

> My suggestions for improving the project: add possibility to input TSID in both decimals or hex

I'll do when I have sufficient time, as this doesn't improve the functionality.

> My suggestions for improving the project: support for modulation entry in IPTV_MappingList.INI for each channel (optional) which will be displayed in Config GUI

This is impossible! The modulation is controlled by the "client" not by the HDHR device. You see QAM64 in the HDHR Config GUI because this tool is requesting to tune a8qam64-*. The emulator only checks the frequency, regardless of modulation request. Try to use the commandline version (hdhomerun_config) and check the results!

> I also tried the Android app InstaTV

Thank you! I'll try.
Another good player for Windows that works is the SichboPVR: http://sichbopvr.com/

> Can you test this one please with DVB-T or DVB-S?

My suggestion is that you try to emulate an HDHR DVB-T and use DVB-C in your Mapping List. It will be more compatible with any client.

> Do you also get this error? Is this normal behaviour?

Yes and Yes. This is normal and a known behaviour. This message is because the emulator doesn't implement anything about the UPnP HTTP API included in recent HDHR devices. So, don't worry about it! Doesn't matter! It's only an informative message.

Regards.

**Comment by ghost** [comment]
@dsaupf 
Thanks for your fast replies and your help! Much appreciated!
I will follow your suggestion for DVB-T. Probably you're right about compatibility.
I will try SchiboPVR, thanks! ;-)

Besides SchiboPVR you also can add NextPVR (https://www.nextpvr.com) to your list of working applications! Also, this one supports both HDHomeRun and SAT>IP (minisatip).

I'm glad you're willing to update the tool for decimal notation of tsid. Indeed no high priority.

Good luck with this project!
I now close this issue :-)
Regards!

**Comment by retrofan1979** [comment]
Hmmm, when streaming the signal stops after about 15 seconds. What could this be and how to prevent this?
