### ISSUE TITLE
Bug: PID Filtering (DVBLink TVSource)

### ISSUE THREAD

**Issue by ghost** [vdomin/HDHRProxyIPTV#5]
@dsaupf:
Hi, with HDHomeRun tools from the Silicondust drivers I can stream succesfully without interruption with for example VLC. However, when installing DVBLink TVSource [From now on referring with DT], I see PID filtering goes wrong. Only pids 0 and 1 are processed with ExternalPIDFiltering=Y.
I'm using minisatip.

Could you please check why DT (internal DVBLink Player and DVBLink DLNA TV Server) doesn't work correctly with PID filtering? Maybe a bug in HDHRProxyIPTV as DT already supports HDHomeRun for a long time?

By the way: channelscan goes fine with DT, very strange, as then also PID filtering is needed to get all channels.

**Comment by retrofan1979** [comment]
Channel scan goes fine:

![001](https://user-images.githubusercontent.com/30625590/29747868-64411834-8b08-11e7-8645-e209de4f901b.PNG)

Tuning goes wrong (no pid filtering) with minisatip:

![002](https://user-images.githubusercontent.com/30625590/29747871-7b249012-8b08-11e7-940b-a140775ecab8.PNG)

Can you please fix this issue? Thanks

**Comment by ghost** [comment]
It's a problem with DVBLink TVSource. With WMC no problems.
